const mongoose = require('mongoose');

const RISK_LEVELS = ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'];

/**
 * RiskAssessment stores a full, auditable breakdown of each risk calculation.
 * Extended in v2.0 with environmentalRisk, vulnerabilityScore, priorityScore,
 * explanationId, and modelVersion for full auditability.
 *
 * IMPORTANT: These scores are prototype/public-health monitoring parameters.
 * They are NOT medically validated diagnostic thresholds.
 */
const riskAssessmentSchema = new mongoose.Schema(
  {
    // Location
    state: { type: String, required: true, trim: true },
    district: { type: String, required: true, trim: true },
    village: { type: String, required: true, trim: true },

    // Component scores (each normalized 0–100)
    symptomScore: { type: Number, required: true, min: 0, max: 100 },
    growthScore:  { type: Number, required: true, min: 0, max: 100 },
    waterScore:   { type: Number, required: true, min: 0, max: 100 },
    clusterScore: { type: Number, required: true, min: 0, max: 100 },

    // v2.0 extended components
    environmentalRisk:  { type: Number, min: 0, max: 100, default: 0 },
    vulnerabilityScore: { type: Number, min: 0, max: 100, default: 0 },

    // Weights used at calculation time (stored for auditability)
    weightsSnapshot: {
      symptom: { type: Number, default: 0.40 },
      growth:  { type: Number, default: 0.25 },
      water:   { type: Number, default: 0.20 },
      cluster: { type: Number, default: 0.15 },
    },
    priorityWeightsSnapshot: {
      risk:          { type: Number, default: 0.60 },
      environmental: { type: Number, default: 0.20 },
      vulnerability: { type: Number, default: 0.20 },
    },

    // Final composite score and level
    riskScore:  { type: Number, required: true, min: 0, max: 100 },
    riskLevel: {
      type: String,
      enum: { values: RISK_LEVELS, message: 'Invalid risk level' },
      required: true,
    },

    // v2.0: priority score (risk + environmental + vulnerability weighted)
    priorityScore: { type: Number, min: 0, max: 100, default: 0 },

    // Linked explanation (generated by explanationService)
    explanationId: { type: mongoose.Schema.Types.ObjectId, ref: 'RiskExplanation' },

    // Linked data quality assessment
    dataQualityId: { type: mongoose.Schema.Types.ObjectId, ref: 'DataQualityAssessment' },

    // Model version for reproducibility
    modelVersion: { type: String, default: 'risk-engine-v1' },

    // Data window used
    dataWindowDays: { type: Number, default: 7 },

    // Audit fields
    calculatedAt: { type: Date, default: Date.now },
    reportCount: { type: Number, default: 0 }, // number of reports that contributed
  },
  {
    timestamps: false, // calculatedAt is explicit
  }
);

riskAssessmentSchema.index({ village: 1, calculatedAt: -1 });
riskAssessmentSchema.index({ district: 1, calculatedAt: -1 });
riskAssessmentSchema.index({ riskLevel: 1 });
riskAssessmentSchema.index({ priorityScore: -1 });
riskAssessmentSchema.index({ calculatedAt: -1 });

module.exports = mongoose.model('RiskAssessment', riskAssessmentSchema);
